Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,15 +10,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
+    - name: Print Directory Structure
+      run: ls -R
     - uses: actions/setup-node@v4
       with:
         node-version: lts/*
+    - name: Check for package.json
+      run: |
+        if [ ! -f package.json ]; then
+          echo "package.json is missing"
+          exit 1
+        fi
     - name: Check for package-lock.json
       run: |
         if [ ! -f package-lock.json ]; then
           npm install
-          git add package-lock.json
-          git commit -m "Add package-lock.json"
         fi
     - name: Install dependencies
       run: npm ci
